schema_version = "1.0.0"

id = "renderwake"
name = "RenderWake"
version = "1.2.7"
tagline = "Keeps your computer awake while Blender renders"
maintainer = "Richies 3D Ltd"
type = "add-on"

# Works on 3.6 LTS onward.
blender_version_min = "3.6.0"

license = ["SPDX:GPL-3.0-or-later"]

website = "https://richies.uk"  
# repository = "https://github.com/stef1949/RenderWake"    

[tags]
category = "System"
